### ISSUE TITLE
 integration: core.rtcpeerconnection Sends messages across data channels failed

### ISSUE THREAD

**Issue by klazizpro** [freedomjs/freedom-for-firefox#43]
>> integration: core.rtcpeerconnection Sends messages across data channels failed
>> Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 10154)
>> integration: core.rtcpeerconnection Checks that Firefox actually signals data channel closing.
pending
>> integration: core.rtcpeerconnection Closes Cleanly failed
>> Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 10154)
>> integration: core.rtcpeerconnection getStats works failed
>> Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 10154)

**Comment by willscott** [comment]
Dup of #29
