### ISSUE TITLE
rename integration task to avoid naming collision with freedom-for-chrome

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-firefox#46]
We would like to add integration tests for both Chrome Firefox add-ons but the relevant task name in both freedom-for-chrome and freedom-for-firefox is integration, making this impossible. We should rename the task, e.g. `integration_firefox`.

Related:
https://github.com/freedomjs/freedom-for-chrome/issues/57

**Comment by soycode** [comment]
I believe this was resolved by grunt-jasmine-firefoxaddon et al.
