### ISSUE TITLE
core.rtcpeerconnection should run in a DOM Window

### ISSUE THREAD

**Issue by bemasc** [freedomjs/freedom-for-firefox#48]
[According to the Firefox WebRTC devs](https://bugzilla.mozilla.org/show_bug.cgi?id=1122687#c24),
> If you want to do WebRTC stuff, you basically need to run it in a DOM window.

We've been seeing a lot of issues, like https://github.com/uProxy/uproxy/issues/663, which seem to be because we are using WebRTC in a context that is basically unsupported by the Firefox team.

We should restructure freedom-for-firefox to run in the way expected by the Firefox developers.

**Comment by willscott** [comment]
App's window is a chromewindow, not a dom window, iirc. Code is also structured as a JSM, which runs as a singleton (as in, 1 instance across addons), and doesn't have a handle back to the specific addon.  I remember that there is something called 'hiddenDOMWindow'. would that be enough? I'm not sure what the specific problem is that this solves though.

Happy to take pull requests to restructure to something we think is saner longer term, but not sure that a high level discussion here makes sense without full understanding of limitations imposed by the code.

**Comment by willscott** [comment]
I believe we've been able to stabilize the rtc connections by taking ownership of the arraybuffers.  This doesn't seem to be a pressing issue, so closing until we have a reason it's needed.
