### ISSUE TITLE
Errors on Shippable tests

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom-for-firefox#50]
>> unit: core.tcpsocket connects failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> unit: core.tcpsocket rejects listens on open ports passed
>> unit: core.tcpsocket receives data failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> unit: core.tcpsocket secures socket with starttls failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> unit: core.udpsocket binds passed
>> unit: core.udpsocket receives data passed
>> integration-single: social.loopback.json logs in passed
>> integration-single: social.loopback.json returns clients passed
>> integration-single: social.loopback.json returns users passed
>> integration-single: social.loopback.json sends message passed
>> integration-single: social.loopback.json ERRCODE-OFFLINE passed
>> integration-single: social.loopback.json ERRCODE-LOGIN_ALREADYONLINE passed
>> integration-single: social.loopback.json ERRCODE-SEND_INVALIDDESTINATION passed
>> integration-single: social.ws.json logs in passed
>> integration-single: social.ws.json returns clients passed
>> integration-single: social.ws.json returns users passed
>> integration-single: social.ws.json sends message passed
>> integration-single: social.ws.json ERRCODE-OFFLINE passed
>> integration-single: social.ws.json ERRCODE-LOGIN_ALREADYONLINE passed
>> integration-single: social.ws.json ERRCODE-SEND_INVALIDDESTINATION passed
>> integration-double: social.ws.json A-B: sends message between A->B passed
>> integration-double: social.ws.json A-B: sends roster updates through the onChange event. passed
>> integration-double: social.ws.json A-B: can return the roster passed
>> integration: storage.isolated.json sets and gets keys passed
>> integration: storage.isolated.json set returns old value passed
>> integration: storage.isolated.json removes a key failed
>> Expected [  ] to equal [  ].
>> integration: storage.isolated.json lists keys that have been set passed
>> integration: storage.isolated.json resolves 'null' when getting unset keys passed
>> integration: storage.isolated.json clears the store passed
>> integration: storage.isolated.json sets work across keys passed
>> integration: storage.isolated.json shares data between different instances
pending
>> integration: storage.shared.json sets and gets keys passed
>> integration: storage.shared.json set returns old value passed
>> integration: storage.shared.json removes a key failed
>> Expected [  ] to equal [  ].
>> integration: storage.shared.json lists keys that have been set passed
>> integration: storage.shared.json resolves 'null' when getting unset keys passed
>> integration: storage.shared.json clears the store passed
>> integration: storage.shared.json sets work across keys passed
>> integration: storage.shared.json shares data between different instances
pending
>> integration: transport.webrtc.json generates signals passed
>> integration: transport.webrtc.json sends a small amount of data. passed
>> integration: transport.webrtc.json chunks data passed
>> integration: transport.webrtc.json sends through multiple tags passed
>> integration: core.rtcpeerconnection Sends string messages across data channels passed
>> integration: core.rtcpeerconnection Sends binary messages across data channels passed
>> integration: core.rtcpeerconnection Checks that Firefox actually signals data channel closing.
pending
>> integration: core.rtcpeerconnection Closes Cleanly passed
>> integration: core.rtcpeerconnection getStats works failed
>> Expected 0 to be greater than 0.
>> integration: core.rtcpeerconnection Signals 'onClose' when created with incorrect parameters passed
>> integration: core.xhr calling open with async=false returns an error passed
>> integration: core.xhr calling open with async=undefined is all good passed
>> integration: core.xhr getReadyState properly returns state passed
>> integration: core.xhr can GET github.com passed
>> integration: core.tcpsocket Works as a Client failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> integration: core.tcpsocket Gets info on client & server sockets failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> integration: core.tcpsocket Sends from Client to Server failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> integration: core.tcpsocket Gives error when connecting to invalid domain failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 12040)
>> integration: core.udpsocket Connects, has state, and sends/receives data passed
>> integration: core.oauth - progresslistener Generates a token passed
>> integration: core.oauth - httpobserver Generates a token passed
Warning: Task "report-tests:fromBuild" failed. Use --force to continue.

**Comment by willscott** [comment]
TCP issues here have been resolved  per #51 

Several remaining bugs like
```
storage.*.json removes a key failed
Expected [ ] to equal [ ].
```

```
integration: core.rtcpeerconnection getStats works failed
Expected 0 to be greater than 0.
```

**Comment by soycode** [comment]
The "expected [ ] to equal [ ]" is resolved with: https://github.com/freedomjs/freedom/commit/a99f483d395760350c4d522ae8833e3be59a540e

core.rtcpeerconnection getStats is still broken, some notes here: https://github.com/willscott/webrtc-adapter/issues/4

And most importantly at the moment, many of the TCP tests are failing (https://github.com/freedomjs/freedom-for-firefox/issues/57#issuecomment-93548921). It seems like all the tests that require both a client and server socket fail, which is presumably at least partially the fault of the test (as the actual live issue is some missing emits but not a total break of connectivity).

The client socket fails to connect to the server socket in the tests with error ` {"errcode":"CONNECTION_FAILED", "message":"Firefox Connection Failed: NS_ERROR_CONNECTION_REFUSED"}` - could have something to do with the mocking or the general test setup/util.

I'll focus on fixing the actual event emit issue as higher priority than the tests, but obviously any thoughts on the tests are welcome too.

**Comment by soycode** [comment]
https://github.com/freedomjs/freedom-for-firefox/pull/60 and https://github.com/freedomjs/freedom/pull/267 combined allow pause/resume to pass (locally for me at least). There were a handful of issues (for instance, the 'in' syntax apparently didn't work in the Firefox addon context), and I also ended up commenting out the client onDisconnect invocation - obviously not ideal, but I don't believe it is what uProxy is depending on at the moment either.

Will investigate more, thoughts/review welcome. Thanks.

**Comment by soycode** [comment]
With #66, Shippable is happily green.
