### ISSUE TITLE
TCP tests fail on firefox 36

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom-for-firefox#51]
```
>> integration: core.tcpsocket Gives error when connecting to invalid domain failed
>> ReferenceError: socketTransportService is not defined in resource://jid1-mkagayemb0e5nq-at-jetpack/freedom_for_firefox_tests/data/spec.jsm (line 11980)
```

Appears that the call to `getService` is failing to return an object as expected.

Definition of the service appears to still exist:
http://mxr.mozilla.org/mozilla-central/source/netwerk/base/nsISocketTransportService.idl

I still see this in a lot of code that mozilla has written
https://dxr.mozilla.org/comm-central/source/chat/modules/socket.jsm#582

and don't see other examples of how you get access to sockets in JSM's.

Probably need to see if there's some other thing needed to properly make calls to ` .getService`
since this seems more broadthan just the transport service.  @trevj reports also seeing failure at
https://github.com/freedomjs/freedom-for-firefox/blob/master/providers/client_socket.js#L4

**Comment by soycode** [comment]
Investigating - for the tests at least it looks like it's not failing directly on those lines (as it does instantiate the socket and it does have all the methods it should in its proto), but does fail immediately when any method of the socket is attempted to be called.

One thing I've been trying is passing an argument to getService for the mainThread (as with the socketTransportService). From [poking through docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_bindings/XPConnect/xpcshell/HOWTO) I found:

    const threadManager = Components.classes["@mozilla.org/thread-manager;1"]
                        .getService(Components.interfaces.nsIThreadManager);
    const mainThread = threadManager.mainThread;

However, this didn't fix/change anything (though it still feels "more consistent", maybe). The [socket transport service docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsISocketTransportService) provide an example that's already exactly like ours.

Obviously, more investigation required, will update as appropriate.

**Comment by willscott** [comment]
Firefox  36 appears to introduce additional compartmentalization of addons.  I'm having trouble tracking down what that actual means in practice, though.

**Comment by soycode** [comment]
One possibility. Per [https://blog.mozilla.org/addons/2015/01/13/compatibility-for-firefox-36/](addon compatibility notes), "const should be block-scoped" - I went ahead and changed socketTransportService and mainThread to var (not an ideal solution of course but just to see if things changed) and now all core.tcpsocket tests pass except "Pause and Resume work."

**Comment by willscott** [comment]
great! that will unblock @bemasc  to implement the pause and resume ones.

**Comment by willscott** [comment]
"pause and resume" were added to freedom's head, and are currently being implemented in chrome and node. firefox impl should come soon, but was blocked on this issue.

**Comment by soycode** [comment]
Gotcha - then yeah, I'd say just switch those to var for now. If we really want them to be const then we may have to figure out whatever spot to explicitly pass them between scopes.
