### ISSUE TITLE
Are we e10s yet?

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom-for-firefox#52]
Firefox is moving to a multi-process world, which will have ramifications on addon behavior.  We should consider these changes and test against Electrolysis.

http://arewee10syet.com/

**Comment by soycode** [comment]
This is getting a bit more imminent (first quarter 2016).

**Comment by soycode** [comment]
Tested with Firefox Nightly and the test suite in this repo passes (or at least all the same tests pass as currently pass in non-nightly Firefox). Leaving this issue open though as there may be needed changes not covered by our test suite (i.e. uProxy dependencies, etc.).

**Comment by soycode** [comment]
Just to note - this is fairly imminent now (August 2nd FF48 will have electrolysis by default). I believe it will go smoothly, but will wait to close this out until the release is official and tests still pass.

**Comment by soycode** [comment]
It's been out for a few weeks and the sky hasn't fallen, so I'm calling this resolved.
