### ISSUE TITLE
onDisconnect dispatch causes uProxy to close connection

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom-for-firefox#61]
The issue is arising from a callback to onInputStreamReady that doesn't have data and so closes the socket (https://github.com/freedomjs/freedom-for-firefox/blob/master/providers/client_socket.js#L46). The last possibly relevant thing I see in the logs right beforehand is:

    console.log: uproxy-firefox: Updating global settings to {"description":"","stunServers":
    [{"url: ["stun:stun.services.mozilla.com"]},{"urls":["stun:stun.stunprotocol.org"]},
     {"urls":["stun:stun.l.google.com:19302"]},{"urls":["stun:stun1.l.google.com:19302"]},
     {"urls":["stun:stun2.l.google.com:19302"]},{"urls":["stun:stun3.l.google.com:19302"]},
     {"urls":["stun:stun4.l.google.com:19302"]}],"hasSeenSharingEnabledScreen":false,
    "hasSeenWelcome":true,"allowNonUnicast":false,"mode":0,"version":1,"statsReportingEnabled":false}

    console.log: uproxy-firefox: UI sending Command {"cmd":"emit","type":1015,"data":
    {"description":"","stunServers":[{"urls":["stun:stun.services.mozilla.com"]},
    {"urls":["stun:stun.stunprotocol.org"]},{"urls":["stun:stun.l.google.com:19302"]},
    {"urls":["stun:stun1.l.google.com:19302"]},{"urls":["stun:stun2.l.google.com:19302"]},
    {"urls":["stun:stun3.l.google.com:19302"]},
    {"urls":["stun:stun4.l.google.com:19302"]}],"hasSeenSharingEnabledScreen":false,
    "hasSeenWelcome":true,"allowNonUnicast":false,"mode":0,"version":1,"statsReportingEnabled":false},
    "promiseId":0}

I think this error probably was happening pre-0.6.11, it's just now we actually dispatch onDisconnect whenever we think the socket was closed, and so the error makes it as far as uProxy and actually causes it to give up.

**Comment by soycode** [comment]
The (client) socket is closing normally (`NS_BASE_STREAM_CLOSED`) apparently for reason of not having any bytes left to read, so it's not an error per se - however with the new logic, any and all socket closes result in dispatching an onDisconnect. The possibilities I can conceive:

- The socket shouldn't be closing at all
- The socket should be closing but uProxy doesn't expect an onDisconnect dispatch from *all* socket closes
- The socket should be closing and dispatch an onDisconnect but is somehow dispatching it to the "wrong" place (corresponding to a different socket or such)

For now I'm going to assume/investigate more the first possibility, but thoughts are welcome on the latter two. In any case, to reiterate I do believe this socket.close call was happening before, and apparently isn't fatal to the uProxy process, it's just now the onDisconnect causes it to be noticed.

**Comment by iislucas** [comment]
@trevj : Can you sync with @soycode to see what we want here. I would expect all socket closes should result in disconnect events.

**Comment by trevj** [comment]
Yes, all socket closes should dispatch `onDisconnect` event.

What I just noticed is that the Firefox provider doesn't pass any argument to the `onDisconnect` event:
https://github.com/freedomjs/freedom-for-firefox/issues/63

This messes up the SOCKS proxy a little and may be the culprit here, too.

**Comment by soycode** [comment]
Tracing through from the other direction, the actual uProxy shutdown occurs due to:

    [XMPPSocialProvider] E [May 5 11:19:42.502] Received unexpected end event
    [XMPPSocialProvider] E [May 5 11:19:42.504] received close event,

This is happening at https://github.com/freedomjs/freedom-social-xmpp/blob/master/src/core/socialprovider.js#L188 which means that the social provider is receiving an `end` event - presumably sent by uProxy due to uProxy receiving the `onDisconnect`.

**Comment by soycode** [comment]
It's not uProxy, but rather freedom-social-xmpp that is receiving the onDisconnect and closing the socket - https://github.com/freedomjs/freedom-social-xmpp/blob/4bc8d3596b350a4de0010b67d377dd183af1b971/lib/tcp.js#L11

So the path seems to be:
 1. the tcp socket gets `onInputStreamReady` with an empty stream, resulting in `NS_BASE_STREAM_CLOSED`
 2. the tcp provider dispatches `onDisconnect`
 3. the social (xmpp) provider receives the `onDisconnect` and executes `onread(-1)`, actually closing the socket and shutting down the social provider
 4. uProxy sees the lack of the social provider and shuts down

The last three steps all make sense, so the problem still lies in the first step (or before). It's not clear to me why the socket is receiving an event w/empty input stream, or if that should always mean a disconnect (or if there are situations where it doesn't).

**Comment by soycode** [comment]
The flow I've described in the previous path is the bug as I've reproduced it - there was some discussion earlier in the standup that the bug may be different when logging in with Facebook (perhaps only triggering when proxying actually starts). If anyone has more information about this let me know, for now I will focus on this particular flow.

**Comment by willscott** [comment]
Right. It seems like this initial error manifests both on the xmpp stream, but also on proxying streams.

**Comment by soycode** [comment]
So we think this is a fix: https://github.com/freedomjs/freedom-for-firefox/commit/474515de8fab3952ee45a0513ca02ea1a96ba143

Securing a socket in Firefox means making a new socket, and evidently abandoning the old one was resulting in it dispatching onDisconnect. This change fixes that and I'm now able to stay logged in to uProxy. I'm actually still having issues proxying, though:

    remote-connection W [May 14 14:23:48.548] Invalid signal:  SIGNAL_FROM_SERVER_PEER

I've tried a few different accounts and directions and am still getting the issue, I think it may be unrelated. If someone wants to work with me to test we can get these changes merged.
