### ISSUE TITLE
onDisconnect dispatch should indicate which "side" closed the socket

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-firefox#63]
The interface specifies that onDisconnect supplies an argument:
https://github.com/freedomjs/freedom/blob/master/interface/core.tcpsocket.json#L76

Firefox doesn't supply this, at least in the case of a normal disconnect.

**Comment by soycode** [comment]
Commit w/default argument (same as Chrome provider): https://github.com/freedomjs/freedom-for-firefox/commit/62838b847a3425612825777b25bdadd2600cbf97

Definitely should also use all the same error mappings as Chrome, but it'd be good to get HEAD working w/uProxy again first.

**Comment by soycode** [comment]
Same as #57, this should be resolved in current freedom-for-firefox (i.e. once https://github.com/uProxy/uproxy/pull/1545 is merged the fix will be in uProxy).

**Comment by soycode** [comment]
So info should now at least be included when dispatching onDisconnect, but it is true that it is not very informative info (always CONNECTION_CLOSED). I'll refocus this issue on distinguishing how the socket was closed.

**Comment by soycode** [comment]
I believe this issue still needs resolution, here's a stab at that - https://github.com/freedomjs/freedom-for-firefox/pull/74

I'm not quite sure if it will behave as expected in uProxy, so my plan is to build and test it more specifically. Thoughts/feedback/review also welcome - thanks!
