### ISSUE TITLE
TCP provider rewrite

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom-for-firefox#64]
Goals:
- Unify server/client logic as much as possible
- Line up with freedom interface/Chrome implementation (on things like errors, etc.)
- "Future-proof" within reason (due diligence that we're using proper browser primitives etc.)

On that last note, I think it is now (or soon will be) possible to use https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mozTCPSocket within a webworker (see also https://bugzilla.mozilla.org/show_bug.cgi?id=504553). This should make things much nicer.

As per usual, this issue is for my occasional notes/updates, and hopefully a pull request ready for review by early-mid next week. Comments/feedback welcome though, especially if you have any reasons to caution against mozTCPSocket or advise towards a different direction.

**Comment by soycode** [comment]
mozTCPSocket definitely looks like the "right way" to do things, but it doesn't quite line up with the raw sockets API yet (http://www.w3.org/TR/raw-sockets/). Of note, the W3 spec gives ways to get both local and remote host/port (needed to implement getInfo), but the mozTCPSocket API looks to only have remote. It also is privileged/requires permissions - not dissimilar to the situation in Chrome, but worth noting.

**Comment by soycode** [comment]
So this will actually be available in webworkers in FIrefox 38 (https://developer.mozilla.org/en-US/Firefox/Releases/38). It's still privileged and so may be disabled by default in some situations, but my hope is that at least for freedom-for-firefox we can make the default manifest specify the permission.

**Comment by willscott** [comment]
Hopefully the webworkers off the hidden background page, rather than the
chromeworkers are what's meant by that.

**Comment by soycode** [comment]
I think we've made peace with how the sockets work now - they're a bit ugly, but per @bemasc more performant/lower-level control.
