### ISSUE TITLE
close method on TCP sockets is broken

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-firefox#77]
Easily verifiable with the echo server sample in uproxy-lib:
https://github.com/uProxy/uproxy-lib#echo-server

When I telnet to the echo server and type ctrl-D, the connection does not close (this works fine in Chrome).

Related:
https://github.com/freedomjs/freedom-for-firefox/issues/72

**Comment by trevj** [comment]
I just performed some testing with the echo server and it looks like this has been broken since freedom-for-firefox 0.6.14.

**Comment by trevj** [comment]
I believe the problem is this commit:
https://github.com/freedomjs/freedom-for-firefox/commit/e3128782ecdc769e99e17ff9ef35e76cac1418c6

@soycode, can you remember why you added this line?

**Comment by soycode** [comment]
I think it may have been to pass this test: https://github.com/freedomjs/freedom/blob/master/spec/providers/coreIntegration/tcpsocket.integration.src.js#L207

That said, at least one issue I see with it now is that it may need to track whether or not the existing connection is in fact active, somewhat along the lines of: https://github.com/freedomjs/freedom-for-node/commit/dbcc1600accf4a70ba27a122bd0a7dbf63b6259e#diff-c02bde11d55bcda45d0a199ac895aef8

**Comment by trevj** [comment]
OK, I have a fix coming your way in a sec.
